#!/bin/bash
# Run as root to install the displaycameras package for streaming video feeds.
# Systemd init system is presumed.  If installing on 'nix with other init
# systems, you will have to edit this script or enable the displaycameras
# service with available tools for your init system.  The main script,
# normally installed at /usr/bin/displaycameras has an LSB header and will run
# as a systemv init script (if copied to /etc/init.d/).  No other init systems
# have been tested.

# What is the path to the installer?
DIR=`dirname "$(readlink -f "$0")"`

# Ensure prerequisites are installed.
if [ -r /etc/os-release ]; then
	. /etc/os-release
fi

remote_access=false
four_camera_layout=false
viewport=false
display_user="${SUDO_USER:-pi}"
if [ "$display_user" = "root" ]; then
	display_user=pi
fi
for arg in "$@"
do
	if [ "$arg" = "--remote-access" ]; then
		remote_access=true
	fi
	if [ "$arg" = "--four-camera-layout" ]; then
		four_camera_layout=true
	fi
	if [ "$arg" = "--viewport" ]; then
		viewport=true
	fi
done

write_four_camera_layout() {
	layout=/etc/displaycameras/layout.conf.default
	if [ ! -r "$layout" ]; then
		echo "No installed layout was found at $layout."
		return 1
	fi
	backup="$layout.bak.`date +%Y%m%d%H%M%S`"
	cp -f "$layout" "$backup"
	echo "Backed up the existing layout to $backup"
	name_line="`sed -n 's/^camera_names=(\(.*\)).*/\1/p' "$layout" | head -1`"
	parsed_names=()
	if [ "$name_line" != "" ]; then
		read -r -a parsed_names <<< "$name_line"
	fi
	parsed_feeds=()
	while IFS= read -r line
	do
		case "$line" in
		*rtsp://*|*rtsps://*)
			feed="${line%%#*}"
			feed="${feed%\\}"
			feed="${feed#"${feed%%[![:space:]]*}"}"
			feed="${feed%"${feed##*[![:space:]]}"}"
			feed="${feed%\"}"
			feed="${feed#\"}"
			feed="${feed%\'}"
			feed="${feed#\'}"
			feed="`printf '%s\n' "$feed" | sed 's/\\\\\([?&=:/@]\)/\1/g'`"
			parsed_feeds+=("$feed")
			;;
		esac
	done < "$layout"
	selected_names=()
	selected_feeds=()
	for i in "${!parsed_feeds[@]}"
	do
		case "${parsed_feeds[$i]}" in
		""|"<Camera stream URL>"|rtsp://user:password@camera-*.example/stream)
			echo "Skipping placeholder feed for ${parsed_names[$i]:-Camera$((i+1))}"
			continue
			;;
		esac
		selected_names+=("${parsed_names[$i]:-Camera$((i+1))}")
		selected_feeds+=("${parsed_feeds[$i]}")
		if [ "${#selected_feeds[@]}" -eq 4 ]; then
			break
		fi
	done
	if [ "${#selected_feeds[@]}" -lt 4 ]; then
		echo "Found only ${#selected_feeds[@]} real camera feed(s). Add four RTSP URLs to $layout and rerun."
		return 1
	fi
	camera_names=("${selected_names[@]}")
	camera_feeds=("${selected_feeds[@]}")
	for i in 0 1 2 3
	do
		echo "Using ${camera_names[$i]} in position $((i+1))"
	done
	{
		echo "# Four-camera 2x2 layout generated by install.sh --four-camera-layout"
		echo "windows=(upper_left upper_right lower_left lower_right)"
		echo
		echo "window_positions=("
		printf '%s\n' '"0 0 959 539" \'
		printf '%s\n' '"960 0 1919 539" \'
		printf '%s\n' '"0 540 959 1079" \'
		printf '%s\n' '"960 540 1919 1079" \'
		echo ")"
		echo
		printf 'camera_names=('
		for i in 0 1 2 3
		do
			printf '%q ' "${camera_names[$i]}"
		done
		echo ")"
		echo
		echo "camera_feeds=( \\"
		for i in 0 1 2 3
		do
			printf '"%s" \\\n' "${camera_feeds[$i]}"
		done
		echo ")"
		echo
		echo 'rotate="false"'
	} > "$layout"
	chown root:root "$layout"
	chmod 0644 "$layout"
}

if [ "$VERSION_CODENAME" = "trixie" ] || ! apt-cache show omxplayer >/dev/null 2>&1; then
	packages="mpv ffmpeg socat fbi util-linux"
	player_backend="mpv"
else
	packages="omxplayer fbi"
	player_backend="omxplayer"
fi

if [ "$viewport" = "true" ]; then
	packages="$packages python3-gi python3-gst-1.0 gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav"
fi

if [ "$remote_access" = "true" ]; then
	packages="$packages x11vnc"
fi

for package in $packages
do
if [ "`dpkg-query -s $package | grep Status | awk -v N=4 '{print $4}'`" != "installed" ]; then
	apt-get install $package -y
fi
done

# Put the files in place and set ownership and permissions.

if [ -r $DIR/displaycameras ]; then
	echo "Copying the main script and setting permissions."
	cp -f $DIR/displaycameras /usr/bin/ && chown root:root /usr/bin/displaycameras && chmod 0755 /usr/bin/displaycameras
else
	echo "The displaycameras file is missing or unreadable. This is a critical file."
	echo "Verify package contents."
	exit 1
fi
if [ -r $DIR/displaycameras.service ]; then
	echo "Copying the systemd init file and setting permissions."
	cp -f $DIR/displaycameras.service /etc/systemd/system/ && chown root:root /etc/systemd/system/displaycameras.service && chmod 0644 /etc/systemd/system/displaycameras.service
else
	echo "The displaycameras.service file is missing or unreadable. This is a critical file."
	echo "Verify package contents."
	exit 2
fi
if [ -r $DIR/displaycameras-boot.timer ]; then
	echo "Copying the boot timer and setting permissions."
	cp -f $DIR/displaycameras-boot.timer /etc/systemd/system/ && chown root:root /etc/systemd/system/displaycameras-boot.timer && chmod 0644 /etc/systemd/system/displaycameras-boot.timer
fi
if [ "$viewport" = "true" ]; then
	if [ -r $DIR/displayviewport ]; then
		echo "Copying the viewport script and setting permissions."
		cp -f $DIR/displayviewport /usr/bin/ && chown root:root /usr/bin/displayviewport && chmod 0755 /usr/bin/displayviewport
	else
		echo "The displayviewport file is missing or unreadable."
		exit 2
	fi
	if [ -r $DIR/displayviewport.service ]; then
		echo "Copying the viewport systemd service and setting permissions."
		cp -f $DIR/displayviewport.service /etc/systemd/system/ && chown root:root /etc/systemd/system/displayviewport.service && chmod 0644 /etc/systemd/system/displayviewport.service
	else
		echo "The displayviewport.service file is missing or unreadable."
		exit 2
	fi
fi
# Config files, cron job, gpu memory split, and disable overscan support only if not upgrading
if [ "$1" != "upgrade" ]; then
	if [ -r $DIR/displaycameras.conf ]; then
		if [ -r /etc/displaycameras/displaycameras.conf ]; then
			[ -d /etc/displaycameras/bak ] || mkdir /etc/displaycameras/bak
			for i in `find /etc/displaycameras/ -maxdepth 1 -type f`; do
				mv -f $i /etc/displaycameras/bak/
			done
			echo "Your config files were backed up to /etc/displaycameras/bak"
		fi
		echo "Copying the global and layout configuration files."
		[ -d /etc/displaycameras ] || mkdir /etc/displaycameras
		cp -f $DIR/layout.conf.default /etc/displaycameras/ && chown root:root /etc/displaycameras/layout.conf.default && chmod 0644 /etc/displaycameras/layout.conf.default
		cp -f $DIR/displaycameras.conf /etc/displaycameras/ && chown root:root /etc/displaycameras/displaycameras.conf && chmod 0644 /etc/displaycameras/displaycameras.conf
		sed -i "s/^#player_backend=.*/player_backend=$player_backend/" /etc/displaycameras/displaycameras.conf
		sed -i "s/^#display_user=.*/display_user=$display_user/" /etc/displaycameras/displaycameras.conf
	else
		echo "The displaycameras.conf file is missing or unreadable. This is a critical file."
		echo "Verify package contents."
		exit 3
	fi
	if [ -r $DIR/repaircameras.cron ]; then
		echo "Copying the repaircameras cron job and reloading cron."
		cp -f $DIR/repaircameras.cron /etc/cron.d/repaircameras && chown root:root /etc/cron.d/repaircameras && chmod 0755 /etc/cron.d/repaircameras
		systemctl restart cron
	else
		echo "The repaircameras.cron file is missing or unreadable. This is a critical file."
		echo "Verify package contents."
		exit 4
	fi
	if [ "$player_backend" = "omxplayer" ] && command -v raspi-config >/dev/null 2>&1 && [ -r /boot/config.txt ]; then
		# Set a reasonable GPU memory allocation
		# Determine total physical memory
		# System Memory
		sysmem="`free -m | grep Mem: | awk '$1=$1' | cut -f 2 -d " "`"
		# GPU Memory
		gpumem="`sudo raspi-config nonint get_config_var gpu_mem /boot/config.txt`"
		# Total Mem
		physmem=$((gpumem + sysmem))
		if [ "$physmem" -lt "500" ]; then
			split=96
			else
			if [ "$physmem" -lt "1000" ]; then
				split=192
				else
				split=256
			fi
		fi
		# Ask whether there's a custom split desired
		echo -n "Enter a custom gpu split if desired [gpu memory in MB] or [Enter] to use recommended split"
		read
		if [ "$REPLY" != "" ]; then
			if [ "$REPLY" -ge "64" -a "$REPLY" -le "512" ]; then
				split="$REPLY"
			fi
		fi
		# Set the split
		if [ "`raspi-config nonint get_config_var gpu_mem /boot/config.txt`" -lt "$split" ]; then
			echo "Setting gpu_mem allocation to "$split"MB"
			raspi-config nonint do_memory_split "$split"
		fi
		# Disable overscan support so that display resolution autodetection works
		if [ "`raspi-config nonint get_overscan`" = "0" ]; then
			echo "Disabling display overscan compensation. Set your monitor not to overscan."
			raspi-config nonint do_overscan 1
		fi
	else
		echo "Skipping legacy gpu_mem and overscan changes for the $player_backend backend."
	fi
fi
if [ -r /etc/displaycameras/displaycameras.conf ]; then
	if ! grep -q '^player_backend=' /etc/displaycameras/displaycameras.conf; then
		echo "player_backend=$player_backend" >> /etc/displaycameras/displaycameras.conf
	fi
	if ! grep -q '^display_user=' /etc/displaycameras/displaycameras.conf; then
		echo "display_user=$display_user" >> /etc/displaycameras/displaycameras.conf
	fi
	if [ "$player_backend" = "mpv" ]; then
		if grep -q '^mpv_grid=' /etc/displaycameras/displaycameras.conf; then
			sed -i 's/^mpv_grid=.*/mpv_grid=true/' /etc/displaycameras/displaycameras.conf
		else
			echo "mpv_grid=true" >> /etc/displaycameras/displaycameras.conf
		fi
	fi
	if [ "$viewport" = "true" ] && ! grep -q '^viewport_fps=' /etc/displaycameras/displaycameras.conf; then
		echo "viewport_fps=8" >> /etc/displaycameras/displaycameras.conf
		echo "viewport_latency_ms=150" >> /etc/displaycameras/displaycameras.conf
		echo "viewport_retry_seconds=5" >> /etc/displaycameras/displaycameras.conf
		echo "viewport_rtsp_protocol=tcp" >> /etc/displaycameras/displaycameras.conf
	fi
fi
if [ "$four_camera_layout" = "true" ]; then
	write_four_camera_layout
fi
if [ -r $DIR/omxplayer_dbuscontrol ]; then
	echo "Copying the omxplayer control script."
	cp -f $DIR/omxplayer_dbuscontrol /usr/bin/ && chown root:root /usr/bin/omxplayer_dbuscontrol && chmod 0755 /usr/bin/omxplayer_dbuscontrol
else
	echo "The omxplayer_dbuscontrl file is missing or unreadable. This is a critical file."
	echo "Verify package contents."
	exit 5
fi
if [ -r $DIR/rotatedisplays ]; then
	echo "Copying the display rotating script and setting permissions."
	cp -f $DIR/rotatedisplays /usr/bin/ && chown root:root /usr/bin/rotatedisplays && chmod 0755 /usr/bin/rotatedisplays
else
	echo "The rotatedisplays file is missing or unreadable. This file is required to support display rotation."
	echo "Verify package contents."
fi
if [ -r $DIR/black.png ]; then
	echo "Copying the black background file and setting ownership."
	cp -f $DIR/black.png /usr/bin/ && chown root:root /usr/bin/black.png
else
	echo "The black.png file is missing or unreadable. Screen blanking will not work"
	echo "with out it.  Verify package contents."
fi

if [ "$remote_access" = "true" ]; then
	if [ -r $DIR/displaycameras-vnc.service ]; then
		echo "Copying the optional remote access service."
		cp -f $DIR/displaycameras-vnc.service /etc/systemd/system/ && chown root:root /etc/systemd/system/displaycameras-vnc.service && chmod 0644 /etc/systemd/system/displaycameras-vnc.service
		systemctl daemon-reload
		systemctl enable displaycameras-vnc
	else
		echo "displaycameras-vnc.service is missing; skipping remote access setup."
	fi
fi

# Update systemd and enable the displaycameras service.
systemctl daemon-reload
if [ "$viewport" = "true" ]; then
	systemctl stop displaycameras >/dev/null 2>&1 || true
	systemctl disable displaycameras >/dev/null 2>&1 || true
	systemctl disable displaycameras-boot.timer >/dev/null 2>&1 || true
	systemctl enable displayviewport
else
	systemctl reenable displaycameras
	systemctl enable displaycameras-boot.timer
fi

echo "Installation Successful!"
if [ "$viewport" = "true" ]; then
	echo "Viewport mode is enabled. Start it now with: sudo systemctl restart displayviewport"
else
	echo "Start it now with: sudo systemctl restart displaycameras"
fi
exit 0
